---
- hosts: all
  pre_tasks:
    - set_fact:
        utility_registry_url: "{{ utility_registry_url|default('localhost:5000') }}"
        utility_docker_command_become: "{{ utility_docker_command_become|default(false) }}"
  tasks:
    - block:
      - name: Login given registry
        command: docker login --username {{ utility_docker_login_user }} --password-stdin {{ utility_registry_url }}
        args:
          stdin: "{{ utility_docker_login_password }}"
        when: (utility_docker_login_user is defined) and (utility_docker_login_password is defined)
      - name: Create a tag starting with repository url
        command: docker tag {{ utility_docker_image }} {{ utility_registry_url }}/{{ utility_docker_image }}
      - name: Push a Docker image to given repository
        command: docker push {{ utility_registry_url }}/{{ utility_docker_image }}
      - name: Remove a tag starting with repository url
        command: docker rmi -f {{ utility_registry_url }}/{{ utility_docker_image }}
      become: "{{ utility_docker_command_become|bool }}"
