---
- hosts: all
  pre_tasks:
    - set_fact:
        utility_registry_url: "{{ utility_registry_url|default('localhost:5000') }}"
        utility_docker_command_become: "{{ utility_docker_command_become|default(false) }}"
  tasks:
    - block:
      - name: Create a tag starting with repository url
        command: docker tag {{ utility_docker_image }} {{ utility_registry_url }}/{{ utility_docker_image }}
      - name: Push a Docker image to given repository
        command: docker push {{ utility_registry_url }}/{{ utility_docker_image }}
      - name: Remove a tag starting with repository url
        command: docker rmi -f {{ utility_registry_url }}/{{ utility_docker_image }}
      become: "{{ utility_docker_command_become|bool }}"
